language: java
notifications:
  hipchat:
    rooms:
      secure: K4dQSHKGH7p9w3r6s92czFReJ+eJMTfqfOtI9/5G7mSyjRTusB5GseoDJIy2AgLAyRUH+9rU0eWhvNgenXyo1J4K43A69meN0+zP3nyJaoiQGYCQVa0O9WRnoLaHUlwqKu6hBMAhCEwoknZqQOB/62Lt3n91tdOjCMfj/aRNz0GlyxlgLnmJ85MouZXC9l1tzP4IJrf/pjUKyTOdqhOXlU6mZ/hVagCFqbWNvqzfriVJUGtFI/x6xRidOAuffxoW5kB3+A+baj6ajujXHULHBP6aHtchSsmsecAPzgIWEItevIHaBu7bQMgtY2/eC2kv/xtpQ4hkskVKTJoxmYQNsErzM9aIqdD1E65QZ2xY8LZvHY+v8bl44TsGBlc0t/pDmVBozYBEeP2PebTbNm9PxmXDhPrwWvYi9XpsLpjAF80dfQ7VQDRepKpxuXYVKhOpbgchzObgCOy4Zb24BCJd6h5iaL9EdQQjkC0+sHRVQx+epcwITxBcAqeyvgmL+6Fxp36i35fyBPiV4pldKXwH6+HeUZyXGth1spwMmVzH50iMsz0TvLhAsKVgXoDjq6ys5CGfREpKSDUklSbfoHdELoeX0W69vYLt3SSoT1qSPTe6LjNzr4UJpe8EjnKGSZIduhQAAgmN0xRVqns4MJDGNgwjGyJDzKUvh+yfukzF1Sk=
deploy:
  provider: releases
  api_key:
    secure: BGGvOSQs8LyPERGQsnGuWjsFGab87lfsJ/ZPTcwKSa5BNos4/b0M5EO+/uEnwUnwQ0wsNgTXBPc7Fuag17JgfufJR7xlVBwkJgBUWQHneqhDdh2057dnE150wGfxusLTlf5TzyUOUxBT4+xpaYCCx8lHMNu/8LkastiS/ESe4hlO1OGhmk8gF7TD6vLpOA3x2l7/3c7PLEUbyZWvxqj3mgosPFtS+v80cg242fUtPugoLApWTxH88fjcmnVBbRq1RBq+0htwhacwGVvizWyhdC+fi1F1zF+++yKlo7DeoaPg8uP6s60ik9wubIf0IEDHyztG8iCbYfv56U42ql5TjQf7nvwH0YfGx4UsfLAuqYiJOpYtJFMSTieQnJXAKtMkpIW4Ngu/nYeAtzvjqWZUK1rhqO4l81NDeuRwS+OIVXO1gXgoD2MvDlx6TXPutrnEOBTKlu5XJDTy6BaKWwqGTrYOYHzCS+JBZUlhQHGa7ZGr1hLy8LxdPwV03JfM8Ib1xGx7N/KKc0+l/cOlgzHCg/IwwH4iFXUajv4b8OXE8nKY/xY2ErBQ6fp1KkZJ/Q7zC63BW19o3mCH/ZF+AIlC24KJPTxNlm33HBOzo9hzroKpcIrODnOjbJi1+tBLXcpV4AirAYhWZuI0ooNdFbOyVxQ0XY7MDf++oaemrqTB5dg=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-wls-server-start-config-plugin

