language: java
notifications:
  hipchat:
    rooms:
      secure: K4dQSHKGH7p9w3r6s92czFReJ+eJMTfqfOtI9/5G7mSyjRTusB5GseoDJIy2AgLAyRUH+9rU0eWhvNgenXyo1J4K43A69meN0+zP3nyJaoiQGYCQVa0O9WRnoLaHUlwqKu6hBMAhCEwoknZqQOB/62Lt3n91tdOjCMfj/aRNz0GlyxlgLnmJ85MouZXC9l1tzP4IJrf/pjUKyTOdqhOXlU6mZ/hVagCFqbWNvqzfriVJUGtFI/x6xRidOAuffxoW5kB3+A+baj6ajujXHULHBP6aHtchSsmsecAPzgIWEItevIHaBu7bQMgtY2/eC2kv/xtpQ4hkskVKTJoxmYQNsErzM9aIqdD1E65QZ2xY8LZvHY+v8bl44TsGBlc0t/pDmVBozYBEeP2PebTbNm9PxmXDhPrwWvYi9XpsLpjAF80dfQ7VQDRepKpxuXYVKhOpbgchzObgCOy4Zb24BCJd6h5iaL9EdQQjkC0+sHRVQx+epcwITxBcAqeyvgmL+6Fxp36i35fyBPiV4pldKXwH6+HeUZyXGth1spwMmVzH50iMsz0TvLhAsKVgXoDjq6ys5CGfREpKSDUklSbfoHdELoeX0W69vYLt3SSoT1qSPTe6LjNzr4UJpe8EjnKGSZIduhQAAgmN0xRVqns4MJDGNgwjGyJDzKUvh+yfukzF1Sk=
deploy:
  provider: releases
  api_key:
    secure: A4Hwu9FVPOfJ7DP61q8SzWnLa4SRkpOLLq8o8LvZUsiwF0TwObcqeXCc1lixayJqvYZrwJH/6Zb4m6v2RpCzxKVJ9rt4FReEyCxJIxCULcd9/lLptSzyiNzr/fF0OV6018B1jjMY7T0bHnp5snAwm/LdTnRDVVhkFWlGQ8cBKW/huNwFSCsgMrAxEH4KVVdges2F3VUtWYzhjkTzz5C8RaiN7h/qx4T0tz93gJfNr9X3lRMnWQLLjOTgwbhsCeH3ygmuTpQ+qSCOD4kFDfpZbg3RyVTS57G9Tz4eS/LTFL8g9VovtXgIIvHCdV99aR1g3crCabULSGpgqsR380OkbgaJd7dwQh9WjmWWeXLyDO8veH/r/NoHCfA7MbkB5oCqiSbJ8+F9091ZJ2nkavsuek0ChbdZ0Ey0dnyrfih81SRowsiCu1jRi8lPk4Gz/VwCIOKf9uV/i9f+0sM5DC/O29GYYge3WauFrspZnMqSkHyZUD7PLVLhqXu8vIgwcND4meLqTztWZkKdvaPrAmSh3LyOjcNr2UPNwKA0sl1hQigAGQry9rVElafT0EiTwoLsFu1a4g6S39HGXiQee5MaBXN2OZ/+7mGnCwLipYZ63Xjy7POVU3euWEMRk68JFRYiz2wlo6Bq/N2AXX3N+GlabKy9iXI7A05MOypjeZIWLug=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-wls-server-start-config-plugin

