language: java
notifications:
  slack:
    secure: NLwYP1QkjJrv/fz7rM8BDWA3Y5SnurPNVLDDXK7tVlwDhElnIQ6dVs6QSbChvFv3P+vdAOyCGVQV4NN3lbuND1/8NmufOr5E0Eun79fpREhZfniVH7UHnCExVdbDz+zYW/3EaY75Hy7BVQYYT16XjNmfBQpPEgWb0J3EeV7L5Xv6vuPLI3T9j3aXq/2DxYyqxmIHCgvoTmGp/4Y+R9OHOQqHGkrHjFCm85r1rsR77ZbMrZz3R7UD7byzV4jS2q0zdFHrBIFl3LMUreyMqLVYgkrX781eAJ8qjGB9jSzOCcucH++MI9f5EyJyN9kqQXihDBPCQ8aw5CXKTEFsVy3Nlh+de6EtszkUljiaNksDWrIF01via0R7GUhF4Q3amJkRxc4BTDdYK8R1+g8JCR4W3P1Yjt2zi/lMxkmeQXcQmEjK9CYe2YCzKRC6wCeNEq5aqNRiWmiXGdyH32c3GC4czu3yNAry/SISLAAFrw/zNz2kmU1JfmIpfciVc/q0Ra9aZWxVLVFUrawiiSqYsTRE3JhplvwIDRCUVN6ZZpxZ+POS7Lanl/8u5mVo4jiZloXf787lEgeQbSTEms+cBUEG4/gwFNuCjDC5Ge6kLYIcRuzNbaoTG4VZdd43huaGDgcMx8Fm1RYaERi1Zb0sfUnGX2jNgiK0HAAl3uLDWLac9Gg=
deploy:
  provider: releases
  api_key:
    secure: BGGvOSQs8LyPERGQsnGuWjsFGab87lfsJ/ZPTcwKSa5BNos4/b0M5EO+/uEnwUnwQ0wsNgTXBPc7Fuag17JgfufJR7xlVBwkJgBUWQHneqhDdh2057dnE150wGfxusLTlf5TzyUOUxBT4+xpaYCCx8lHMNu/8LkastiS/ESe4hlO1OGhmk8gF7TD6vLpOA3x2l7/3c7PLEUbyZWvxqj3mgosPFtS+v80cg242fUtPugoLApWTxH88fjcmnVBbRq1RBq+0htwhacwGVvizWyhdC+fi1F1zF+++yKlo7DeoaPg8uP6s60ik9wubIf0IEDHyztG8iCbYfv56U42ql5TjQf7nvwH0YfGx4UsfLAuqYiJOpYtJFMSTieQnJXAKtMkpIW4Ngu/nYeAtzvjqWZUK1rhqO4l81NDeuRwS+OIVXO1gXgoD2MvDlx6TXPutrnEOBTKlu5XJDTy6BaKWwqGTrYOYHzCS+JBZUlhQHGa7ZGr1hLy8LxdPwV03JfM8Ib1xGx7N/KKc0+l/cOlgzHCg/IwwH4iFXUajv4b8OXE8nKY/xY2ErBQ6fp1KkZJ/Q7zC63BW19o3mCH/ZF+AIlC24KJPTxNlm33HBOzo9hzroKpcIrODnOjbJi1+tBLXcpV4AirAYhWZuI0ooNdFbOyVxQ0XY7MDf++oaemrqTB5dg=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-wls-server-start-config-plugin
